// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CategoriesList: typeof import('./src/components/categories/CategoriesList.vue')['default']
    CategoryRow: typeof import('./src/components/categories/CategoryRow.vue')['default']
    ConfirmationComponent: typeof import('./src/components/common/ConfirmationComponent.vue')['default']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    FilterBar: typeof import('./src/components/records/FilterBar.vue')['default']
    ModalComponent: typeof import('./src/components/common/ModalComponent.vue')['default']
    NavigationComponent: typeof import('./src/components/NavigationComponent.vue')['default']
    PageContent: typeof import('./src/components/common/PageContent.vue')['default']
    RecordRow: typeof import('./src/components/records/RecordRow.vue')['default']
    RecordsList: typeof import('./src/components/records/RecordsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveCategory: typeof import('./src/components/categories/SaveCategory.vue')['default']
    SaveRecord: typeof import('./src/components/records/SaveRecord.vue')['default']
  }
}
