export const LOAD_CATEGORIES_SUCCESS = 'category/LOAD_CATEGORIES_SUCCESS';
export const CREATE_CATEGORY_SUCCESS = 'category/CREATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_SUCCESS = 'category/UPDATE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_SUCCESS = 'category/DELETE_CATEGORY_SUCCESS';
