export const BEGIN_AJAX_CALL = 'common/BEGIN_AJAX_CALL';
export const END_AJAX_CALL = 'common/END_AJAX_CALL';

export const CONFIRM_ACTION = 'CONFIRM_ACTION';
export const CONFIRM_ACTION_CANCEL = 'CONFIRM_ACTION_CANCEL';
