export const LOAD_RECORDS_SUCCESS = 'record/LOAD_RECORDS_SUCCESS';
export const CREATE_RECORD_SUCCESS = 'record/CREATE_RECORD_SUCCESS';
export const UPDATE_RECORD_SUCCESS = 'record/UPDATE_RECORD_SUCCESS';
export const DELETE_RECORD_SUCCESS = 'record/DELETE_RECORD_SUCCESS';
